### ISSUE TITLE
No syntax highlight, all blue

### ISSUE THREAD

**Issue by EspetecDev** [mr-ubik/atom-ubik-neon-syntax#2]
Hello, 

saw your post on /r/unixport and decided to try it. After installing it it just shows all text in blue, I use Seti as a UI Theme. 

[Imgur](http://i.imgur.com/2Dajkkj.png)
any suggestions? Thanks :D

**Comment by mr-ubik** [comment]
Which version of Atom are you running? Be Sure to update to the new 1.13 version.

**Comment by EspetecDev** [comment]
Resolved updating to 1.13 (automatic updating was not finding any new version on v 1.12)

Thanks!
